spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/canteen?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username:
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: spaceHikariCPPool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      # 连接超时时间（毫秒）
      timeout: 20000
      # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
      database: 0
      # 连接池最大连接数（使用负值表示没有限制） 默认 8
      lettuce:
        shutdown-timeout: 2000ms
        pool:
          max-active: 20
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-wait: 2000
          # 连接池中的最大空闲连接 默认 8
          max-idle: 20
          # 连接池中的最小空闲连接 默认 0
          min-idle: 2

